### ISSUE TITLE
Fails to build due to Rust Issue #44265

### ISSUE THREAD

**Issue by cmahnke** [simoncozens/kurbopy#6]
See https://github.com/cmahnke/font-action/actions/runs/4392194573/jobs/7691822466#step:6:1101

This issue is referenced, i'm not sure wether this is an issue with the wrapper or the wrapped library
https://github.com/rust-lang/rust/issues/44265

If this is related to the library please make sure that the dependencies and tools are used in the right version. and provide hints if those aren't satisfied.

**Comment by simoncozens** [comment]
Yeah, looks like the upstream library implements GATs in https://github.com/linebender/kurbo/pull/231
MSRV is now 1.65; I should clarify that.

I'm not sure why pip isn't picking up the built wheels that we supply; is there any reason these are all being built from source?

**Comment by cmahnke** [comment]
I haven't looked into it, but I use GitHub Actions to build for ARM64 and X86_64. Probably there aren't any pre build binaries for ARM64.

**Comment by simoncozens** [comment]
Then this is now #7 and I'm working on it!
