### ISSUE TITLE
Linux arm64 wheels

### ISSUE THREAD

**Issue by whi-tw** [simoncozens/kurbopy#7]
Hi,

I'm trying to use kurbopy in a linux aarch64 docker container. Would it be possible for you to distribute wheels for this?

maturin [already has a manylinux aarch64 wheel](https://files.pythonhosted.org/packages/8f/16/1f325d18531dda8455bc3411ab17c773079472b4242276e3e6c93ea204fe/maturin-1.1.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_1_aarch64.whl).

Thanks,

Tom

**Comment by simoncozens** [comment]
Could you please test the wheel in https://github.com/simoncozens/kurbopy/suites/13901372597/artifacts/773258304 ? If that's good I'll distribute.

**Comment by cmahnke** [comment]
Any news on this issue? The Link isn't working anymore...

**Comment by simoncozens** [comment]
I'm going to upgrade kurbopy and release with the arm64 wheels.
